---
title: "test KleborateR"
author: "Kat Holt"
date: '2023-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = getwd())
```

### prepare data and call clusters
```{r}
# load clustering functions
source("https://raw.githubusercontent.com/klebgenomics/KleborateR/main/cluster_functions.R")

# load kleborate file and SNP distance file from Pathogenwatch, for BARNARDS Kleb pneumo genomes
kleborate <- readr::read_csv("testdata/barnards-kp-kleborate.csv")
snps <- read_snp_diff("testdata/barnards-kp-difference-matrix.csv")

# assign clusters based on SNPs
data <- get_cluster_membership_from_distmat(kleborate, snps)

# add country
country <- readr::read_csv("testdata/barnards-kp-country.csv")
data <- data %>% left_join(country)

```

# calculate raw and adjusted prevalences

``` {r}
# load kleborate processing functions
source('https://raw.githubusercontent.com/klebgenomics/KleborateR/development/kleborate_functions.R')

```

``` {r}
# to get K locus frequency per country, adjusting for clustering...
# we set grouping_vars = c("Country", "K_locus")
#        summarise_by = "Country"
#        adj_vars="Cluster"
raw_adj_prop(data, grouping_vars = c("Country", "K_locus"), adj_vars = c("Cluster"), summarise_by = "Country")

# if we include site as a grouping variable, we break down some clusters into multiple sites, they are then counted as separate clusters which increases the denominator - ie denominator is number of unique K/Site/clusters per Country, not correct to say the denominator is 'country'
raw_adj_prop(data, grouping_vars = c("Country", "K_locus", "Site"), adj_vars = c("Cluster"), summarise_by = "Country")

# Note that all unique values for the specified variables are counted separately, and 
# contribute to unique variable combinations that will count as separate clusters.
# This means that two strains in the same cluster and country, one with K_locus='KL112' 
# and the other with K_locus='unknown (KL112)' will be counted as 2 distinct clusters.
# THIS SHOULD BE REVIEWED, e.g. strip 'unknown ()' to ignore confidence, except for
# unknown (KL107) which is truly uncallable.

# solution implemented, can switch on by setting clean_Klocus = T
raw_adj_prop(data, grouping_vars = c("Country", "K_locus"), adj_vars = c("Cluster"), summarise_by = "Country", clean_Klocus = T)
```

``` {r}
library(meta)

# pooled estimate for K locus prevalence, across countries
# based on https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/pooling-es.html#pooling-props

barnards_adj <- raw_adj_prop(data, grouping_vars = c("Country", "K_locus"), adj_vars = c("Cluster"), summarise_by = "Country", clean_Klocus = T)

barnards_adj_country_sums <- barnards_adj %>% select(Country, raw_sum, adj_sum) %>% unique()
  
barnards_adj <- barnards_adj %>%
  select(-c(raw_sum, adj_sum)) %>%
  complete(K_locus, Country, fill=list(raw_count=0, adj_count=0, raw_prop=0, adj_prop=0)) %>%
  left_join(barnards_adj_country_sums)

# test with one K locus that was found in all countries, KL62
barnards_adj %>% 
  filter(K_locus=="KL62") %>% 
  metaprop(event=raw_count, n=raw_sum, studlab=Country,  
  method = "GLMM", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE) %>%
  forest.meta(layout="RevMan5")

# from the book above: There are no iron-clad rules determining when exactly further analyses of the between-study heterogeneity are warranted. An approach that is sometimes used in practice is to check for outliers and influential cases when I2 is greater than 50%. When this threshold is reached, we can assume at least moderate heterogeneity, and that (more than) half of the variation is due to true effect size differences.

```

``` {r}

# pool estimates across sites
barnards_adj_site <- raw_adj_prop(data, grouping_vars = c("Country", "K_locus", "Site"), adj_vars = c("Cluster"), summarise_by = "Site", clean_Klocus = T)

barnards_adj_site_sums <- barnards_adj_site %>% select(Site, Country, raw_sum, adj_sum) %>% unique()
  
barnards_adj_site <- barnards_adj_site %>%
  select(-c(raw_sum, adj_sum, Country)) %>%
  complete(Site, K_locus, fill=list(raw_count=0, adj_count=0, raw_prop=0, adj_prop=0)) %>%
  left_join(barnards_adj_site_sums)

barnards_adj_site %>% 
  filter(K_locus=="KL116") %>% 
  metaprop(event=raw_count, n=raw_sum, studlab=Site,  subgroup=Country,
  method = "GLMM", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE) %>%
  forest.meta(layout="RevMan5")

barnards_adj_site %>% 
  filter(K_locus=="KL62") %>% 
  metaprop(event=raw_count, n=raw_sum, studlab=Site,  subgroup=Country,
  method = "GLMM", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE) %>%
  forest.meta(layout="RevMan5")

# plot only the subgroup estimates (ie country effects, pooled across sites) and total estimate, not individual sites
barnards_adj_site %>% 
    filter(K_locus=="KL62") %>% 
    metaprop(event=raw_count, n=raw_sum, studlab=Site,  subgroup=Country,
             method = "GLMM", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE) %>%
    forest.meta(layout="RevMan5", study.results=F)

# we could similarly use subgroups to pool sites across regions

# As we want to combine our estimates across studies, some of which will have multiple sites, so we need a study*site variable, that is used as our studlab

```