---
title: "calculate prevalences for Kp NNS"
author: "Kat Holt"
date: '2023-06-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = getwd())

library(ggplot2)
library(tidyverse)
library(dplyr)
```

# calculate raw and adjusted prevalences

``` {r}
# load kleborate processing functions
source('kleborate_functions.R')

```

``` {r}

data <- read_csv("testdata/kleborate_NNS.csv")

```

``` {r}
include_study <- c("Barnards", "CHAMPS", "CHRF_bangladesh", "GHRU_Nigeria", "heinz_pakistan_2019", "malawi_nns", "spinz")
includ_agegroup <- c("neonatal", "neonate", "neonates")

data_NNS <- data %>% 
  filter(Study %in% include_study) %>% 
  filter(Age_group %in% includ_agegroup) %>%
  genome_filter(k_typable=F, o_typable=F)  # QC on general stats, not intactness of KL/OL

sites_n10 <- data_NNS %>% 
  group_by(Study, Country, Site) %>% 
  summarise(n=n()) %>% 
  filter(n>=10)

# per-site prevalence
site_prevalence <- data_NNS %>% 
  filter(Site %in% sites_n10$Site) %>%
  raw_adj_prop(grouping_vars = c("K_locus", "Site"), summarise_by = "Site", adj_vars = c("Cluster", "Site"))

```

``` {r}
library(meta)

site_prevalence_site_sums <- site_prevalence %>%
  select(Site, raw_sum, adj_sum) %>% unique()

site_country <- data_NNS %>%
  select(Site, Country) %>% 
  unique()

site_prevalence <- site_prevalence %>% 
  select(-c(raw_sum, adj_sum)) %>%
  complete(K_locus, Site, fill=list(raw_count=0, adj_count=0, raw_prop=0, adj_prop=0)) %>%
  left_join(site_prevalence_site_sums, by=c("Site")) %>%
  left_join(site_country, by=c("Site"))

```

``` {r}

  global_est <- read_csv("\n", col_names = c("K_locus", "est", "lower", "upper"))
  country_est <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
  country_est_lower <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
  country_est_upper <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
    
  for (kl in unique(site_prevalence$K_locus)) {
    site_est <- NULL
    
    u <- try(
    site_est <- site_prevalence %>%
      filter(K_locus==kl) %>% 
      metaprop(event=raw_count, n=raw_sum, studlab=Site, subgroup=Country,  
        method = "Inverse", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE),
    silent=T)
    
    if(!is.null(site_est)) {
       global_est <- bind_rows(global_est, 
                               c(K_locus=kl,
                                      est=1/(1+exp(-1*site_est$TE.random)),
                                      lower=1/(1+exp(-1*site_est$lower.random)),
                                      upper=1/(1+exp(-1*site_est$upper.random)) 
                               )
                        )
       country_est <- bind_rows(country_est, 
                                c(K_locus=kl, 1/(1+exp(-1*site_est$TE.random.w))))
       country_est_lower <- bind_rows(country_est_lower, 
                                      c(K_locus=kl, 1/(1+exp(-1*site_est$lower.random.w))))
       country_est_upper <- bind_rows(country_est_upper, 
                                      c(K_locus=kl, 1/(1+exp(-1*site_est$upper.random.w))))
     }
  }
  
country_est_lower <- country_est_lower %>% 
  rename_all(~str_replace_all(., "\\s+", "")) %>%
  rename_with(~paste0(., "_lower"), names(.)) %>% 
  rename(K_locus=K_locus_lower)

country_est_upper <- country_est_upper %>% 
  rename_all(~str_replace_all(., "\\s+", "")) %>%
  rename_with(~paste0(., "_upper"), names(.)) %>% 
  rename(K_locus=K_locus_upper)

results_tab <- full_join(global_est, country_est, by=c("K_locus")) %>%
  full_join(country_est_lower, by=c("K_locus")) %>%
  full_join(country_est_upper, by=c("K_locus"))

write.csv(results_tab, file="Kp_NNS_raw_sitePooled_countrySubgroup.csv", row.names=F)

```


``` {r}

  global_est <- read_csv("\n", col_names = c("K_locus", "est", "lower", "upper"))
  country_est <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
  country_est_lower <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
  country_est_upper <- read_csv("\n", col_names = c("K_locus", unique(site_prevalence$Country)))
    
  for (kl in unique(site_prevalence$K_locus)) {
    site_est <- NULL
    
    u <- try(
    site_est <- site_prevalence %>%
      filter(K_locus==kl) %>% 
      metaprop(event=adj_count, n=adj_sum, studlab=Site, subgroup=Country,  
        method = "Inverse", sm = "PLOGIT", fixed = FALSE, random = TRUE, method.random.ci = TRUE),
    silent=T)
    
    if(!is.null(site_est)) {
       global_est <- bind_rows(global_est, 
                               c(K_locus=kl,
                                      est=1/(1+exp(-1*site_est$TE.random)),
                                      lower=1/(1+exp(-1*site_est$lower.random)),
                                      upper=1/(1+exp(-1*site_est$upper.random)) 
                               )
                        )
       country_est <- bind_rows(country_est, 
                                c(K_locus=kl, 1/(1+exp(-1*site_est$TE.random.w))))
       country_est_lower <- bind_rows(country_est_lower, 
                                      c(K_locus=kl, 1/(1+exp(-1*site_est$lower.random.w))))
       country_est_upper <- bind_rows(country_est_upper, 
                                      c(K_locus=kl, 1/(1+exp(-1*site_est$upper.random.w))))
     }
  }
  
country_est_lower <- country_est_lower %>% 
  rename_all(~str_replace_all(., "\\s+", "")) %>%
  rename_with(~paste0(., "_lower"), names(.)) %>% 
  rename(K_locus=K_locus_lower)

country_est_upper <- country_est_upper %>% 
  rename_all(~str_replace_all(., "\\s+", "")) %>%
  rename_with(~paste0(., "_upper"), names(.)) %>% 
  rename(K_locus=K_locus_upper)

results_tab_adj <- full_join(global_est, country_est, by=c("K_locus")) %>%
  full_join(country_est_lower, by=c("K_locus")) %>%
  full_join(country_est_upper, by=c("K_locus"))

write.csv(results_tab_adj, file="Kp_NNS_adj_sitePooled_countrySubgroup.csv", row.names=F)

```

``` {r }
# raw prevalence, not adjusted or pooled

raw_global <- data_NNS %>% group_by(K_locus) %>% summarise(n=n(), p=n/nrow(data_NNS))

```

``` {r }
combined <- results_tab %>% 
  select(K_locus, est, lower, upper) %>% 
  rename(est_unadj_pooled=est, lower_unadj_pooled=lower, upper_unadj_pooled=upper) %>%
  full_join(results_tab_adj, by=c("K_locus")) %>%
  rename(est_adj_pooled=est, lower_adj_pooled=lower, upper_adj_pooled=upper)
  
combined <- raw_global %>% rename(est_raw=p, n_raw=n) %>% full_join(combined, by=c("K_locus"))

write.csv(combined, file="Kp_NNS_raw_adj_sitePooled_countrySubgroup.csv", row.names=F)

```